Version management

diff --git a/werk.yml b/werk.yml
--- a/werk.yml
+++ b/werk.yml
@@ -25,3 +25,18 @@ jobs:
     executor: local
     commands:
       - ameba
+
+  version:
+    executor: docker
+    image: mikefarah/yq:4.5.1
+    commands:
+      - >
+        if [ -z ${VERSION+x} ]; then
+          echo "Missing variable VERSION!"
+          echo "Please make sure the variable is set before running this target."
+          exit 1
+        fi
+      - echo "Updating version ${VERSION} ..."
+      - yq eval -i ".version = \"${VERSION}\"" shard.yml
+      - sed -i "s/VERSION = \".*\"/VERSION = \"${VERSION}\"/" src/version.cr
+      - echo "Done."
